### PR TITLE
openvswitch improvements

### PR DESCRIPTION
**Pull request by kmcopper**
- tidy maintainer definition
- add myself to maintainers
- use https for url fetch
- update lts to 2.5.9
- compile with openssl 1.1 (lts and latest)
- use https for homepage url
- use python3 instead of python2 (latest only)

###### Motivation for this change

Improvements to existing pull request

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

cc: @netixx

### CODE REVIEW

**Comment by netixx** [comment]
Looks good to me (and works on my setup)!

Did you have anything more you wanted to add or edit ?

**Comment by netixx** [comment]
Also, I don't really know how to proceed with this "nested PR", since I have an outstanding PR in the upstream https://github.com/NixOS/nixpkgs/pull/53033.
My plan at the moment is to merge this request in my branch and update the upstream PR (and hope for a merge 👍 ).

**Comment by kmcopper** [comment]
Wait for a little bit I'm still working on fixing openssl 1.1 support in the LTS branch. I was planning on doing python3 in lts branch but it seems to be a bit more involved than the openssl fixes I almost have completed.

**Comment by kmcopper** [comment]
Good to go.

**Pull request merged**
